### ISSUE TITLE
Trailing markdown codeblock

### ISSUE THREAD

**Issue by litoj** [JosefLitos/copilot-cmp#1]
Hi @JosefLitos, thank you for the fix. I have some trouble in using this fork version. After hit the enter key to input the completion text, there is always the markdown code chunk marks around the code. One example:

When enter
<img width="318" alt="image" src="https://github.com/zbirenbaum/copilot-cmp/assets/5415510/186441d6-7862-4345-9524-404b5d2affac">

The output become:

<img width="203" alt="image" src="https://github.com/zbirenbaum/copilot-cmp/assets/5415510/7c3e67b7-9d37-4132-8cc6-ff1150b6cdb3">

_Originally posted by @y9c in https://github.com/zbirenbaum/copilot-cmp/issues/105#issuecomment-2078059530_

**Comment by litoj** [comment]
This unfortunately seems to be directly from copilot - this is what comes from the api for `for i in `:

```lua
{
  completions = { {
      displayText = '{1..100}; do\n\techo -n "$i "\ndone',
      docVersion = 245,
      position = <1>{},
      range = <table 1>,
      text = 'for i in {1..100}; do\n\techo -n "$i "\ndone',
      uuid = "fa9f8b8e-60ad-4452-9824-8c9a35a4eb03"
    }, {
      displayText = "$(seq 1 100); do\n\techo $i\ndone\n```\n\n```bash",
      docVersion = 245,
      position = <table 1>,
      range = <table 1>,
      text = "for i in $(seq 1 100); do\n\techo $i\ndone\n```\n\n```bash",
      uuid = "44311928-7ef1-4cef-893a-c20eb4e333d1"
    } }
}
```

When looking into `:Copilot panel` I saw a lot of weird things containing simillar suggestions. Try to see for yourself if it is also there.

But I don't think it shows up for everything. Even in this suggestion you can see the first one was fine, it was just the second one that contains the weird markdown.

So it still can return normal responses, it just doesn't know what to suggest. I also wasn't able to reproduce this anywhere outside an empty file, so it may just be it having too little context.

**Comment by y9c** [comment]
Thank you very much for solving this. I have confirmed that when there is too little content in the file, Copilot adds the markdown block. I used to think the issue might be related to the plugin. However, if the issue is caused by Copilot, I can simply ignore the error.
