### ISSUE TITLE
Documents for update_on_keypress?

### ISSUE THREAD

**Issue by Peeeaje** [JosefLitos/copilot-cmp#2]
First of all, really thank you for creating this fork. The original repository looks not be maintained actively even though there are some bugs or inconviniences.

All problems that I had were solved in this fork, so... Really appreciate it. Tbh my main purpose is to say thank you :) 

But also I thought what does `update_on_keypress` means, I'd like to get the docs on the readme so if I could get some detail for that I'd appreciate. This fork deserves more attention in my opinion.

**Comment by litoj** [comment]
Hi, thank you for the suggestion. I originally thought the option is quite self-explanatory because the only think to update in the plugin is the completion, but I suppose a little extra detail never hurt. I hope it conveys the purpose of the option well enough.
